apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server
  namespace: drone
  labels:
    app.kubernetes.io/component: drone-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-server
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      containers:
        - name: drone-server
          image: public.ecr.aws/cloudpilotai/drone:2
          imagePullPolicy: IfNotPresent
          env:
            - name: DRONE_GITHUB_CLIENT_ID
              value: Ov23liOEUvW0GuJLpB79
            - name: DRONE_GITHUB_CLIENT_SECRET
              value: xxx
            - name: DRONE_RPC_SECRET
              value: hello
            - name: DRONE_SERVER_HOST
              value: drone-server.drone
            - name: DRONE_SERVER_PROTO
              value: http
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 250m
              memory: 250Mi
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: drone-config
              mountPath: /var/lib/drone
      volumes:
        - name: drone-config
          hostPath:
            path: /var/lib/drone
            type: DirectoryOrCreate
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: drone-server
  namespace: drone
  labels:
    app.kubernetes.io/component: drone-server
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: LoadBalancer
  selector:
    app: drone-server
